name: finance_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  go_router: ^16.1.0
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.2.0
  carousel_slider: ^5.1.1
  dots_indicator: ^4.0.1
  fl_chart: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/static/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ThinItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist/static/Urbanist-BlackItalic.ttf